"""Initial migration

Revision ID: 58da464eae59
Revises: 
Create Date: 2025-09-25 08:39:41.141944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58da464eae59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pasien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('umur', sa.Integer(), nullable=False),
    sa.Column('tinggi', sa.Float(), nullable=False),
    sa.Column('riwayat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pemeriksaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('hasil_scan', sa.Text(), nullable=False),
    sa.Column('pasien_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pasien_id'], ['pasien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pemeriksaan')
    op.drop_table('pasien')
    # ### end Alembic commands ###
