"""Initial migration

Revision ID: 682edb7edca3
Revises: 
Create Date: 2025-10-05 23:40:59.430757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '682edb7edca3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasien', schema=None) as batch_op:
        batch_op.drop_column('riwayat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('riwayat', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
